import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Main container with gradient background */}
        <section className="min-h-screen w-full bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
          <SignedOut>
            <div className="text-center space-y-8 max-w-md w-full">
              {/* Welcome message */}
              <div className="space-y-3">
                <h1 className="text-3xl font-bold text-gray-900">Welcome</h1>
                <p className="text-gray-600">Sign up to get started with your account</p>
              </div>
              
              {/* Sign Up Button with better styling */}
              <SignUpButton mode="modal">
                <button className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold py-3 px-6 rounded-lg shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
                  Get Started
                </button>
              </SignUpButton>
              
              {/* Additional options */}
              <div className="text-sm text-gray-500">
                Already have an account?{" "}
                <SignInButton mode="modal">
                  <button className="text-blue-600 hover:text-blue-700 font-medium underline transition-colors duration-200">
                    Sign in
                  </button>
                </SignInButton>
              </div>
            </div>
          </SignedOut>
          
          <SignedIn>
            {/* User button positioned in top right */}
            <div className="fixed top-4 right-4 z-50">
              <UserButton 
                appearance={{
                  elements: {
                    rootBox: "shadow-lg",
                    userButtonAvatarBox: "w-10 h-10",
                    userButtonOuterIdentifier: "text-sm font-medium"
                  }
                }}
              />
            </div>
            
            {/* Children content for signed-in users */}
            {children}
          </SignedIn>
        </section>
      </body>
    </html>
  </ClerkProvider>
);
}